package com.crw.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class SbpProduct implements Serializable {
    private static final long serialVersionUID = 3257312754458967764L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.full_name
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.alias_name
     *
     * @mbg.generated
     */
    private String aliasName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.original_price
     *
     * @mbg.generated
     */
    private BigDecimal originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.vip_price
     *
     * @mbg.generated
     */
    private BigDecimal vipPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.storage
     *
     * @mbg.generated
     */
    private Integer storage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.create_at
     *
     * @mbg.generated
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sbp_product.update_at
     *
     * @mbg.generated
     */
    private Long updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.id
     *
     * @return the value of sbp_product.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.id
     *
     * @param id the value for sbp_product.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.code
     *
     * @return the value of sbp_product.code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.code
     *
     * @param code the value for sbp_product.code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.type
     *
     * @return the value of sbp_product.type
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.type
     *
     * @param type the value for sbp_product.type
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.full_name
     *
     * @return the value of sbp_product.full_name
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.full_name
     *
     * @param fullName the value for sbp_product.full_name
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.alias_name
     *
     * @return the value of sbp_product.alias_name
     * @mbg.generated
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.alias_name
     *
     * @param aliasName the value for sbp_product.alias_name
     * @mbg.generated
     */
    public void setAliasName(String aliasName) {
        this.aliasName = aliasName == null ? null : aliasName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.original_price
     *
     * @return the value of sbp_product.original_price
     * @mbg.generated
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.original_price
     *
     * @param originalPrice the value for sbp_product.original_price
     * @mbg.generated
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.vip_price
     *
     * @return the value of sbp_product.vip_price
     * @mbg.generated
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.vip_price
     *
     * @param vipPrice the value for sbp_product.vip_price
     * @mbg.generated
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.storage
     *
     * @return the value of sbp_product.storage
     * @mbg.generated
     */
    public Integer getStorage() {
        return storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.storage
     *
     * @param storage the value for sbp_product.storage
     * @mbg.generated
     */
    public void setStorage(Integer storage) {
        this.storage = storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.create_at
     *
     * @return the value of sbp_product.create_at
     * @mbg.generated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.create_at
     *
     * @param createAt the value for sbp_product.create_at
     * @mbg.generated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sbp_product.update_at
     *
     * @return the value of sbp_product.update_at
     * @mbg.generated
     */
    public Long getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sbp_product.update_at
     *
     * @param updateAt the value for sbp_product.update_at
     * @mbg.generated
     */
    public void setUpdateAt(Long updateAt) {
        this.updateAt = updateAt;
    }

    public enum ProductType {
        BOOK(1);

        private int value;

        ProductType(int value) {
            this.value = value;
        }

        public int value() {
            return value;
        }
    }
}

