logging.config: classpath:log4j2.xml

# jdbc-DruidDataSource连接池配置
sbp.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/spring-boot-practice?useUnicode=true&amp;characterEncoding=utf8mb4&amp;useSSL=false&amp;autoReconnect=true
  username: root
  password: root
  connection-timeout: 20000
  testWhileIdle: true
  validationQuery: SELECT 1
  timeBetweenEvictionRunsMillis: 300000
  initialSize: 10
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  minEvictableIdleTimeMillis: 300000
  testOnBorrow: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20

# mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration.mapUnderscoreToCamelCase: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql

# rabbitMQ
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# activeMQ
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true

# cache
  cache:
    type: guava