logging.config: classpath:log4j2.xml

# 端口号
server.port: 8081

# jdbc-DruidDataSource连接池配置
sbp.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/spring-boot-practice?useUnicode=true&amp;characterEncoding=utf8mb4&amp;useSSL=false&amp;autoReconnect=true
  username: root
  password: root
  connection-timeout: 20000
  testWhileIdle: true
  validationQuery: SELECT 1
  timeBetweenEvictionRunsMillis: 300000
  initialSize: 10
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  minEvictableIdleTimeMillis: 300000
  testOnBorrow: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20

# mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration.mapUnderscoreToCamelCase: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql

# rabbitMQ
spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

# activeMQ
spring.activemq:
  broker-url: tcp://127.0.0.1:61616
  user: admin
  password: admin
  in-memory: true
  pool:
    enabled: false
  packages:
    trust-all: true

# cache
spring.cache:
  type: redis

# redis
spring.redis:
  database: 2
  host: 127.0.0.1
  port: 6379
  password:
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 0
  enabled: false


# mail
spring.mail:
  host: smtp.qq.com
  username: 120755274@qq.com
  password: 此处需要是授权码
  protocol: smtp
  default-encoding: UTF-8

# swagger配置
swagger:
  title: API接口服务平台
  description: 本平台是XXXX平台。实现了XXX功能。
  license:
  licenseUrl:
  termsOfServiceUrl:
  version: 1.0.0
  basePackage: com.crw

# swagger文档路由
springfox.documentation.swagger.v2.path: /api-docs
# 访问swagger-ui地址: http://host:port/swagger-ui.html

# stream 消息驱动
spring:
  cloud:
    stream:
      bindings:
        input:
          content-type: application/json
          destination: raw-sensor-data
        output:
          destination: raw-sensor-data