package com.crw.mapper;

import com.crw.model.SbpProduct;
import com.crw.model.SbpProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SbpProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    long countByExample(SbpProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int deleteByExample(SbpProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int insert(SbpProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int insertSelective(SbpProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    List<SbpProduct> selectByExample(SbpProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    SbpProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SbpProduct record, @Param("example") SbpProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SbpProduct record, @Param("example") SbpProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SbpProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SbpProduct record);
}