package com.crw.mapper;

import com.crw.model.SbpUser;
import com.crw.model.SbpUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SbpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    long countByExample(SbpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int deleteByExample(SbpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int insert(SbpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int insertSelective(SbpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    List<SbpUser> selectByExample(SbpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    SbpUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SbpUser record, @Param("example") SbpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SbpUser record, @Param("example") SbpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SbpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sbp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SbpUser record);

    List<SbpUser> getAll();

    int insertList(List<SbpUser> list);
}